### ISSUE TITLE
iframe website not displaying

### ISSUE THREAD

**Issue by angiejones** [applitools/the-kitchen#1]
On the [iframe page](https://kitchen.applitools.com/ingredients/iframe), it's now showing the website and instead is showing "refused to connect". 

This error is in the console

```
Refused to frame 'https://www.seriouseats.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.specless.io *.specless.tech http://*.seo.aws.about.com https://*.seo.aws.about.com http://*.dotdash.com https://*.dotdash.com *.seriouseats.com".
```

**Comment by colbyfayock** [comment]
Updated this to in https://github.com/applitools/the-kitchen/commit/1e50a9d01fcf5b064885a7a39523485ad0e5e317 to link the iFrame to the internal Table page
